version: '2'

services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca:1.4.1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.example.com
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key.pem -b admin:adminpw -d'
    volumes:
      - ../config/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org1.example.com

  ca.org2.example.com:
    image: hyperledger/fabric-ca:1.4.1
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org2.example.com
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/key.pem -b admin:adminpw -d'
    volumes:
      - ../config/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.org2.example.com

  orderer-base:
    image: hyperledger/fabric-orderer:1.4.1-minbft-hw
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/orgs.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer/msp
      - SGX_SDK=/opt/intel/sgxsdk
      - SGX_MODE=HW
      # /opt/intel 不要かも
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/opt/intel/sgxsdk/lib64
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    devices:
        - "/dev/sgx:/dev/sgx"
    privileged: true
    volumes:
      - ../config/:/etc/hyperledger/configtx
      - /opt/intel:/opt/intel
      - /usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
      # - /root/tmp/nle-blockchain-fabric/minbft-artifacts:/var/hyperledger/orderer/minbft-artifacts
      - ../minbft-artifacts/consensus.yaml:/var/hyperledger/orderer/minbft-artifacts/consensus.yaml
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
      - /root/tmp/nle-blockchain-fabric/.build/bin/orderer:/usr/local/bin/orderer

  orderer0.example.com:
    extends: orderer-base
    container_name: orderer0.example.com
    environment:
      - MINBFT_REPLICA_ID=0
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer0
    ports:
      - "7050:7050"
      - "7878:7878"
    volumes:
      - ../config/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - ca.org1.example.com
      - ca.org2.example.com

  orderer1.example.com:
    extends: orderer-base
    container_name: orderer1.example.com
    environment:
      - MINBFT_REPLICA_ID=1
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer1
    ports:
      - "8050:7050"
      - "8878:7878"
    volumes:
      - ../config/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - ca.org1.example.com
      - ca.org2.example.com

  orderer2.example.com:
    extends: orderer-base
    container_name: orderer2.example.com
    environment:
      - MINBFT_REPLICA_ID=2
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer2
    ports:
      - "9050:7050"
      - "9878:7878"
    volumes:
      - ../config/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp:/etc/hyperledger/msp/orderer/msp
    depends_on:
      - ca.org1.example.com
      - ca.org2.example.com

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: hyperledger/fabric-peer:1.4.1
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=2org1peercouchdb_default
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org1.example.com:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../config/mychannel.tx:/etc/hyperledger/configtx/mychannel.tx
        - ../config/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/peer/msp
        - ../config/crypto-config/peerOrganizations/org1.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer0.example.com
      - orderer1.example.com
      - orderer2.example.com
      - couchdb.org1.example.com

  couchdb.org1.example.com:
    container_name: couchdb.org1.example.com
    image: hyperledger/fabric-couchdb:latest
    ports:
      - 5984:5984
    environment:
      DB_URL: http://localhost:5984/member_db

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: hyperledger/fabric-peer:1.4.1
    environment:
      - CORE_LOGGING_PEER=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=DEBUG
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=2org1peercouchdb_default
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/peer/msp
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.org2.example.com:5984
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
        - /var/run/:/host/var/run/
        - ../config/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/etc/hyperledger/peer/msp
        - ../config/crypto-config/peerOrganizations/org2.example.com/users:/etc/hyperledger/msp/users
    depends_on:
      - orderer0.example.com
      - orderer1.example.com
      - orderer2.example.com
      - couchdb.org2.example.com

  couchdb.org2.example.com:
    container_name: couchdb.org2.example.com
    image: hyperledger/fabric-couchdb:latest
    ports:
      - 6984:5984
    environment:
      DB_URL: http://localhost:5984/member_db
